listener 1883
allow_anonymous false
password_file C:/iot-cloud-platform/mosquitto/passwd
persistence true
persistence_location C:/iot-cloud-platform/mosquitto/data/
log_dest file C:/iot-cloud-platform/mosquitto/logs/mosquitto.log
log_type all
connection_messages true
max_connections 100
